# https://github.com/marketplace/actions/discord-webhook-action

name: Discord Notify Deploy
on: deployment

jobs:
  discord-notify-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
